### ISSUE TITLE
crash (av1 not working)

### ISSUE THREAD

**Issue by polvallverdu** [polvallverdu/VLCVideo-API-PolCinematics#3]
```
[23:14:25] [Server thread/ERROR] (FancyVideo-API) Invalid instantiation
 java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at nick1st.fancyvideo.api.MediaPlayerHandler.createPlayerForMe(MediaPlayerHandler.java:187) ~[fancyvideo-fabric-310f655470.jar:?]
	at nick1st.fancyvideo.api.MediaPlayerHandler.registerPlayerOnFreeResLoc(MediaPlayerHandler.java:108) ~[fancyvideo-fabric-310f655470.jar:?]
	at dev.polv.polcinematics.client.renders.VideoPlayer.changeMediaPath(VideoPlayer.java:39) ~[1320929404827252721.jar:?]
	at dev.polv.polcinematics.client.renders.VideoPlayer.<init>(VideoPlayer.java:33) ~[1320929404827252721.jar:?]
	at dev.polv.polcinematics.commands.VideoCommand.play(VideoCommand.java:66) ~[1320929404827252721.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.server.command.CommandManager.redirect$bgh000$architectury$performCommand(CommandManager.java:1045) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.command.CommandManager.execute(CommandManager.java:285) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handleCommandExecution(ServerPlayNetworkHandler.java:1341) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.method_44356(ServerPlayNetworkHandler.java:1321) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.method_5386(ThreadExecutor.java:67) ~[minecraft-project-@fabric-merged-named.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:786) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:165) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:768) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:762) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:139) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:747) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:679) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[minecraft-project-@fabric-merged-named.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:181) ~[minecraft-project-@fabric-merged-named.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThreadOrInit(RenderSystem.java:165) ~[minecraft-project-@fabric-merged-named.jar:?]
	at net.minecraft.client.texture.AbstractTexture.getGlId(AbstractTexture.java:39) ~[minecraft-project-@fabric-merged-named.jar:?]
	at nick1st.fancyvideo.api.internal.SelfCleaningDynamicTexture.setImage(SelfCleaningDynamicTexture.java:49) ~[fancyvideo-fabric-310f655470.jar:?]
	at nick1st.fancyvideo.api.mediaPlayer.MediaPlayerBase.<init>(MediaPlayerBase.java:65) ~[fancyvideo-fabric-310f655470.jar:?]
	at nick1st.fancyvideo.api.mediaPlayer.SimpleMediaPlayer.<init>(SimpleMediaPlayer.java:55) ~[fancyvideo-fabric-310f655470.jar:?]
	... 30 more
 @ 000001a283f21a00] Failed to allocate space for current frame.
[av1 @ 000001a283f21a00] Get current frame error
[av1 @ 000001a283f21a00] Failed to get reference frame.
[av1 @ 000001a283f21a00] video_get_buffer: image parameters invalid
[av1 @ 000001a283f21a00] get_buffer() failed
[av1 @ 000001a283f21a00] thread_get_buffer() failed
[av1 @ 000001a283f21a00] Failed to allocate space for current frame.
[av1 @ 000001a283f21a00] Get current frame error
[av1 @ 000001a283f21a00] video_get_buffer: image parameters invalid
[av1 @ 000001a283f21a00] get_buffer() failed
[av1 @ 000001a283f21a00] thread_get_buffer() failed
[av1 @ 000001a283f21a00] Failed to allocate space for current frame.
[av1 @ 000001a283f21a00] Get current frame error
[av1 @ 000001a283f21a00] Failed to get reference frame.
[av1 @ 000001a283f21a00] video_get_buffer: image parameters invalid
[av1 @ 000001a283f21a00] get_buffer() failed
[av1 @ 000001a283f21a00] thread_get_buffer() failed
[av1 @ 000001a283f21a00] Failed to allocate space for current frame.
[av1 @ 000001a283f21a00] Get current frame error
[av1 @ 000001a283f21a00] Failed to get reference frame.
[av1 @ 000001a283f21a00] video_get_buffer: image parameters invalid
[av1 @ 000001a283f21a00] get_buffer() failed
[av1 @ 000001a283f21a00] thread_get_buffer() failed
[av1 @ 000001a283f21a00] Failed to allocate space for current frame.
[av1 @ 000001a283f21a00] Get current frame error
[av1 @ 000001a283f21a00] Failed to get reference frame.
[av1 @ 000001a283f21a00] video_get_buffer: image parameters invalid
[av1 @ 000001a283f21a00] get_buffer() failed
[av1 @ 000001a283f21a00] thread_get_buffer() failed
[av1 @ 000001a283f21a00] Failed to allocate space for current frame.
[av1 @ 000001a283f21a00] Get current frame error
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a283e7d540] decoding for stream 0 failed
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a283e7d540] Could not find codec parameters for stream 0 (Video: av1 (Main), 1 reference frame (av01 / 0x31307661), none(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 10541 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[av1 @ 000001a2a010cac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 000001a2a010cac0] Failed to get pixel format.
[av1 @ 000001a2a010cac0] Missing Sequence Header.
[av1 @ 000001a2a010cac0] Missing Sequence Header.
[av1 @ 000001a2a010cac0] Missing Sequence Header.
[av1 @ 000001a2a010cac0] Missing Sequence Header.
[av1 @ 000001a2a010cac0] Missing Sequence Header.
[av1 @ 000001a2a010cac0] Missing Sequence Header.
[av1 @ 000001a2a010cac0] video_get_buffer: image parameters invalid
[av1 @ 000001a2a010cac0] get_buffer() failed
[av1 @ 000001a2a010cac0] thread_get_buffer() failed
[av1 @ 000001a2a010cac0] Failed to allocate space for current frame.
[av1 @ 000001a2a010cac0] Get current frame error
[av1 @ 000001a2840883c0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 000001a2840883c0] Failed to get pixel format.
[av1 @ 000001a2840883c0] Missing Sequence Header.
[av1 @ 000001a2840883c0] Missing Sequence Header.
[av1 @ 000001a2840883c0] Missing Sequence Header.
[av1 @ 000001a2840883c0] Missing Sequence Header.
[av1 @ 000001a2840883c0] Missing Sequence Header.
[av1 @ 000001a2840883c0] Missing Sequence Header.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2840883c0] get_buffer() failed
[av1 @ 000001a2840883c0] thread_get_buffer() failed
[av1 @ 000001a2840883c0] Failed to allocate space for current frame.
[av1 @ 000001a2840883c0] Get current frame error
[av1 @ 000001a2840883c0] Failed to get reference frame.
[av1 @ 000001a2840883c0] video_get_buffer: image parameters invalid
[av1 @ 000001a2[23:14:36] [Server thread/INFO] (Minecraft) Saving and pausing game...
[23:14:36] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[test]'/minecraft:overworld
[23:14:36] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[test]'/minecraft:the_end
[23:14:36] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[test]'/minecraft:the_nether

```

**Comment by polvallverdu** [comment]
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a283d38600] decoding for stream 0 failed
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a283d38600] Could not find codec parameters for stream 0 (Video: av1 (Main), 1 reference frame (av01 / 0x31307661), none(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 10541 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[av1 @ 000001a29fef4440] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 000001a29fef4440] Failed to get pixel format.
[av1 @ 000001a29fef4440] Missing Sequence Header.
[av1 @ 000001a29fef4440] Missing Sequence Header.

**Comment by polvallverdu** [comment]
need to rebuild ffmpeg https://stackoverflow.com/questions/70828250/ffmpeg-errors-from-converting-mkv-to-mp4

**Comment by polvallverdu** [comment]
Same happening to vp9 too...
